theme: jekyll-theme-architect
description: "Practical ML for Developing Countries Workshop @ ICLR 2021, 
    <br/> Learning under limited/low resource scenarios. Virtual."
basepath: "iclr2021/"
google_analytics: UA-156425047-1

navigation:
- text: HOME
  url: /
- text: CfP
  url: /cfp.html
- text: DATES
  url: /dates.html
- text: PAPERS
  url: /papers.html
  layout: project
- text: ORGANIZERS
  url: /organizers.html
#- text: SCHEDULE
#  url: /schedule.html
#  layout: post
#- text: PAPERS
#  url: /papers.html
#  layout: post
#- text: INSTRUCTIONS
#  url: /instructions.html
#- text: VIRTUAL
#  url: /virtual.html

